### ISSUE TITLE
Issues in Sunbrust Chart

### ISSUE THREAD

**Issue by arjun-naxa** [naxa-developers/sakchyam_client#125]
## Description

- [x] Download button on infographic is not functioning.
- [x] Incorrect placement of toolt and text of different level in expanded view.
- [x] Make infographic non-scrollable in expanded view
- [x] Reset button on both view(Expanded and other)
- [x] Remove the black background.
- [x] Download button on infographic in full-screen view.
- [x] The infographics reset when we goes to expanded view.Should reflect same in both view.
- [x] Legend text of Sunbrust Chart hides

**Comment by varun2948** [comment]
Issue Solved Of Sankey Chart

**Comment by varun2948** [comment]
#125 sorted
