### ISSUE TITLE
Issues In Beneficiaries-Budget Bar Graph

### ISSUE THREAD

**Issue by arjun-naxa** [naxa-developers/sakchyam_client#127]
### Description
- [x] Place "Province" in X-Label and Place Province Name(1,2,3,4 and so on) on X-axis Values.
- [x] Show province name on tool-tip of bar 
- [x] Place exact Male beneficiaries count(From 3K to 3000)
- [x] Remove decimal from female beneficiaries
- [x] Change the title to "Province wise budget and beneficiaries count"
- [x] Change the legend text of total budget to "Budget Allocated"
- [x] Adjust the infographics in full-screen view/Expanded view(Need to scroll horizontally to view province name and legend)
- [x] Place the Filter in expanded view.
- [x] Remove the grid line.
- [x] Place the download button on expanded view.
- [x] Reset Button on expanded view
- [x] Remove reset in first view. Because we need to apply something to reset it to default.
- [x] Only show province bar in card view. But change province bar as per filter applied.
- [x] Adjust range of bar when we reach to municipality level.
- [x] Right side bar is not changing as per graph interaction

- [x] Title of visualization should be as per graph visualized.(District --- Municipality)

**Comment by varun2948** [comment]
#127 Sorted
