### ISSUE TITLE
Reflect left side bar interaction on info-graphics

### ISSUE THREAD

**Issue by arjun-naxa** [naxa-developers/sakchyam_client#130]
## Issues:

- [x] Selection of investment focus is reflected only on Sunbrust(Not on twoGraphs)

- [x] Data Displayed on Province(Beneficiaries/ Budget) after selecting investment focus is not correct.

- [x] Selection of project status is reflected only on bar-graph(Not on sunbrust and leverage-scf fund graph)
- [x] Selection of project is not reflected on Leverage-SCF fund graph
- [x] Selection of partner type is only reflected on sunbrust chart not on other two bar graph.
- [x] Selection of partner institution is not reflected on Leverage-SCF funds graph.

**Comment by varun2948** [comment]
Leverage Project wise only possible
