### ISSUE TITLE
Downloaded chart is not correct.

### ISSUE THREAD

**Issue by arjun-naxa** [naxa-developers/sakchyam_client#204]
### Description

- [x] When we download infographics on an expanded view, the downloaded infographic is not correct(No title and milestone year on the x-axis). 
![Net Increase in Income at Beneficiary Level](https://user-images.githubusercontent.com/67580093/89153445-99be3400-d584-11ea-9ebb-ab9df204f75f.png)

**Comment by varun2948** [comment]
#204 Done
