### ISSUE TITLE
Incorrect number range on y-axis and downloaded infographics

### ISSUE THREAD

**Issue by arjun-naxa** [naxa-developers/sakchyam_client#207]
### Description

- [x] There is an incorrect number range on the y-axis of output indicator 1.2(Individual Count)

- [x] Downloaded infographic is not correct.
![BFIs Provide Improved and Better Services for Enterprises](https://user-images.githubusercontent.com/67580093/89155389-709fa280-d588-11ea-9392-1ac35ade6a24.png)

**Comment by varun2948** [comment]
#207 Completed

**Comment by varun2948** [comment]
Please Check it Once again arjun
