### ISSUE TITLE
Change double Y-axis chart title.

### ISSUE THREAD

**Issue by arjun-naxa** [naxa-developers/sakchyam_client#252]
### Description

- [ ] On the expanded view of the "Province wise budget and beneficiaries count" chart, change the title of infographics when we switch from province to district or from one to another. When we switch from Province to district show "District wise budget and beneficiaries count" on the title of infographics and so on for municipality and vice versa.

**Comment by varun2948** [comment]
Changed The Title To Federal For Overall Every Bar Representation Will Rediscuss if Client Will Suggest To Change For Every Province,District,Municipality
