### ISSUE TITLE
Partner name on tool-tip hides.

### ISSUE THREAD

**Issue by arjun-naxa** [naxa-developers/sakchyam_client#282]
### Description

- [ ] When we play timeline, tool-tip of one partner hides tool-tip of another partner.
![image](https://user-images.githubusercontent.com/67580093/90367228-48379e00-e088-11ea-90cb-493fa90c7dbe.png)

**Comment by palashdevmanandhar** [comment]
Arjun it's gonna take some time and as it isn't a major issue i will do it later.

**Comment by arjun-naxa** [comment]
It's major issue dai.

**Comment by palashdevmanandhar** [comment]
The partner name appears and disappears after 1 second but the problem of the overlapping name still persists. Please review the  development and comment on it .
