### ISSUE TITLE
Font and text alignment on tool-tip

### ISSUE THREAD

**Issue by arjun-naxa** [naxa-developers/sakchyam_client#283]
### Description

- [ ] There should be the proper font, and text alignment on tool-tip when we hover over local units.
![image](https://user-images.githubusercontent.com/67580093/90367877-f8a5a200-e088-11ea-977c-f9c58b4c8bbf.png)

**Comment by varun2948** [comment]
text alignment is adjusted as the sub heading of the Title and font is corrected
