### ISSUE TITLE
Label on sankey hides overlaps each other

### ISSUE THREAD

**Issue by arjun-naxa** [naxa-developers/sakchyam_client#312]
### Description

- [ ] Select Sikhar insurance and develop simple and easy insurance scheme, then go down to sankey chart develop simple and weather index overlaps each other.
![image](https://user-images.githubusercontent.com/67580093/90489895-a5e9ea00-e15d-11ea-8f2e-be551337be35.png)

**Comment by royallsilwallz** [comment]
Collapse Rightsidebar to fix this issue in small screen size
