### ISSUE TITLE
Gap on bottom.

### ISSUE THREAD

**Issue by arjun-naxa** [naxa-developers/sakchyam_client#324]
### Description

- [ ] There is gap on bottom of most of the visualization.
![image](https://user-images.githubusercontent.com/67580093/90592550-8e663c00-e205-11ea-8cfb-7848a02a2775.png)

**Comment by palashdevmanandhar** [comment]
I think Prem dai should have full control over alignment related issues because if we change the css to fix a particular module, it might have unwanted chain reactions in other modules.
