### ISSUE TITLE
Filter is not applied on second level of "Investment Focus Wise Budget & Beneficiaries Count".

### ISSUE THREAD

**Issue by arjun-naxa** [naxa-developers/sakchyam_client#332]
### Description

- [x] When we select investment focus-"Automation of MFIs" and Project-"Inclusive Micro Finance through Digitisation of Business Processes", then click on the bar of "Investment Focus Wise Budget & Beneficiaries Count". After that, all project of "automation of mfis" is displayed instead of "Inclusive Micro Finance through Digitisation of Business Processes".

**Comment by varun2948** [comment]
#332 Check Once
