### ISSUE TITLE
Tool-tip on pie-chart hides

### ISSUE THREAD

**Issue by arjun-naxa** [naxa-developers/sakchyam_client#434]
### Description

- [ ] When we hover over the green color on the pie-chart of the right sidebar, then name of partner on the tool-tip hides.
![image](https://user-images.githubusercontent.com/67580093/91844428-2c7eeb00-ec77-11ea-9549-8ad39036d573.png)

**Comment by varun2948** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Test Issues](https://trello.com/c/K9BOyn3Z/1-test-issues)
