### ISSUE TITLE
The x-axis label on budget vs beneficiaries(Investment Focus) is compact.

### ISSUE THREAD

**Issue by arjun-naxa** [naxa-developers/sakchyam_client#494]
**BUG**
When we click on Outreach expansion on budget vs beneficiaries(Investment Focus), then the product name on the x-axis is compact.

**STEP TO GENERATE ISSUES**
1. Go to "Partnership"
2. Scroll down to "Budget vs Beneficiaries" chart(Investment Focus).
3. Click on "Outreach Expansion"
4. See bug/

**SCREENSHOT**
![image](https://user-images.githubusercontent.com/67580093/96558867-03282600-12dc-11eb-8f7a-0dc83ef1b0de.png)

**Comment by varun2948** [comment]
This has beend discussed with the Client and as there is alot of data with bar and which is not possible at the size of the card so user has to click on extend to see clearly.
