### ISSUE TITLE
Downloaded sankey chart doesnot contain any label.

### ISSUE THREAD

**Issue by arjun-naxa** [naxa-developers/sakchyam_client#498]
**BUG*
The downloaded sankey chart doesnot contain any label. Is it possible to include label on downloaded sankey chart.

**Comment by varun2948** [comment]
I Have Workaround on Sankey By Hovering Over the Sankey The Data Popups Up and Click at the Same Time Will Download The Current State of Sankey With Popup.

**Comment by arjun-naxa** [comment]
@varun2948 the downloaded sankey chart is as follows
![Sakchyam Investment Focus](https://user-images.githubusercontent.com/67580093/97676274-80138680-1ab8-11eb-9fbf-8517291cd2e6.png)
