### ISSUE TITLE
Move the legend down on budget and beneficiaires graph(Investment Focus)

### ISSUE THREAD

**Issue by arjun-naxa** [naxa-developers/sakchyam_client#519]
** BUG **
Move the legend down the visualization.

** Screenshots**
![image](https://user-images.githubusercontent.com/67580093/97689978-7859df00-1ac4-11eb-9f9d-e9d488ca31b7.png)

**Comment by varun2948** [comment]
Legend has been moved to Top Center position for the clear visualization of label of the bar in partnership module.
