### ISSUE TITLE
Need a download and expand button on male and female percentage pie-chart

### ISSUE THREAD

**Issue by arjun-naxa** [naxa-developers/sakchyam_client#525]
** BUG **

There should be a separate download and expand options on male and female percentage pie-chart of outcome indicator 4.

** Screenshots**
![image](https://user-images.githubusercontent.com/67580093/97860033-8fe5d180-1d29-11eb-8de8-0ebf94ce0e90.png)

**Comment by varun2948** [comment]
expand feature is the same as the pie so we might not need expand button for now if client asks we will reopen it.
