### ISSUE TITLE
Increase the width of downloaded right side bar(Result and Selected Partner)

### ISSUE THREAD

**Issue by arjun-naxa** [naxa-developers/sakchyam_client#534]
** BUG **
When we download the right sidebar data(Result and Selected partner), the downloaded image is too thinner. Can we increase the width a bit larger.

** SCREENSHOTS **
![image](https://user-images.githubusercontent.com/67580093/97975011-8bd0b700-1df0-11eb-84b3-ae7497de0b93.png)

**Comment by varun2948** [comment]
this is a portrait div so it will download the way it is.
