### ISSUE TITLE
Displaying two value for beneficiaries: N/A and 39280 when we apply partner and province filter  & Reset button is not functioning after filter is applied.

### ISSUE THREAD

**Issue by arjun-naxa** [naxa-developers/sakchyam_client#536]
** BUG **
When we select a partner and then province, then on the right sidebar there is showing two different values on the result section and selected partner section.

** STEPS TO GENERATE ISSUES **
1. Go to "Automation"
2. Toggle Off: Coverage
3. Select Kisan Microfinance.
4. See error 1.
5 Try pressing Reset on left side bar
6. See error 2.

** Screenshots **
![image](https://user-images.githubusercontent.com/67580093/97977338-2c74a600-1df4-11eb-954a-b6bdd0dfaa67.png)

**Comment by varun2948** [comment]
https://sakchyam.naxa.com.np/api/v1/automation/automation-partner/?filter_type=partner&partner=16&province=1 
ISSUE ON BENEFICIARY VALUE FROM API NEED TO SORT IT OUT
