### ISSUE TITLE
Partner on right side bar get's filtered for no reason.

### ISSUE THREAD

**Issue by arjun-naxa** [naxa-developers/sakchyam_client#537]
** BUG **
When we select a partner from the left sidebar and then apply the province filter, then the partner on the right side gets filtered automatically.

** STEPS TO GENERATE ISSUES **
1. Go to "Automation"
2. Toggle off: Coverage
3. Select Kisan Microfinance from the left sidebar.
4. Select Province 1
5. See left sidebar

**Comment by varun2948** [comment]
https://sakchyam.naxa.com.np/api/v1/automation/automation-partner/?filter_type=partner&partner=16&province=1 
issue on beneficiary number when it is supposed to be 0
