### ISSUE TITLE
On heat map, x-axis value cuts on window modal.

### ISSUE THREAD

**Issue by arjun-naxa** [naxa-developers/sakchyam_client#542]
### BUG

On the Modal window of heat map, the value on x-axis cuts.

### Screenshots
![image](https://user-images.githubusercontent.com/67580093/98108053-7ed0c800-1ec3-11eb-9379-922f133c6a95.png)

**Comment by arjun-naxa** [comment]
@varun2948 can we make it fit in that modal window? Now we have to scroll to look at market failure.

**Comment by varun2948** [comment]
scroll is needed otherwise the yaxis gets overlapped so it will have to be scrollable for small screen other than that it fits in big screen, so it should not be a problem.
