### ISSUE TITLE
Need to make heat map non-scrollable.

### ISSUE THREAD

**Issue by arjun-naxa** [naxa-developers/sakchyam_client#550]
**BUG**
On the window modal of the heat map, we need to scroll vertically to view the complete heat map. Need to make it non-scrollable.

**STEPS**
1. Go to the window modal of heat map.
2. See error.

**SCREENSHOT**
![image](https://user-images.githubusercontent.com/67580093/98227840-e5b3b700-1f7f-11eb-8dd3-42ca67876dea.png)

**Comment by arjun-naxa** [comment]
@varun2948 x-axis value is taking too much space therefore the text on y-axis overlapping each other. What to do bhayo :thinking: ?

![image](https://user-images.githubusercontent.com/67580093/99036091-25deef00-25a9-11eb-974f-b0c1d5b20cd6.png)

**Comment by varun2948** [comment]
Scrolling is needed on small screen so i have increased the height .
