### ISSUE TITLE
Geographical filter is not applied on second level(Key Innovation).

### ISSUE THREAD

**Issue by arjun-naxa** [naxa-developers/sakchyam_client#586]
**BUG**
The geographical filter is not applied to key innovation stacked chart that appear after we click on partner bar.

**STEP TO GENERATE ISSUES**
1. Select province 1
2. Scroll down to a stacked chart.
3. Click on the partner bar.

**Screenshot**
![image](https://user-images.githubusercontent.com/67580093/98347281-51108e00-203f-11eb-97e5-b6a1fc7bb463.png)

**Comment by arjun-naxa** [comment]
@varun2948 when we click on reset button on stacked chart, reset only stacked chart. Here, clicking on stacked chart reset button resets geographical filter as well.

**STEP**
1. Applied above mention steps.
2. Click on Reset of stacked chart.
3. See error.

**Comment by varun2948** [comment]
Reset Button Resets Every Filters So This should be Fine

**Comment by varun2948** [comment]
left Side Reset has to reset both filter as assigned in other module aswell
